spring:
    application:
        name: lotteshop
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Password1!
        url: jdbc:mysql://43.200.184.246/farmstory_4
        username: abc1234
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: false
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true

    # 이메일 설정
    mail:
        host: smtp.gmail.com
        port: 587
        username: kdehgogo104@gmail.com
        password: tovh lfoa vshl lmdd
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true

    thymeleaf:
        cache: false
        check-template-location: true
        prefix: classpath:/templates
        suffix: .html
        enabled: true
    security:
        oauth2:
            client:
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        user-name-attribute: id
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent

                registration:
                    kakao:
                        client-name: kakao
                        authorization-grant-type: authorization_code

                        # 카카오 > 내 애플리케이션 > 카카오 로그인 > 등록한 Redirect URI 입력
                        redirect-uri: http://43.200.184.246:8080/lotteshop/oauth2/authorization/kakao

                        # 카카오 > 내 애플리케이션 > 요약정보 > REST API 키 입력
                        client-id: b7032bdbb25b0dfef4cdfd81e9ba089e

                        # 카카오 > 내 애플리케이션 > 카카오 로그인 > 보안 > Client Secret 생성 후 입력
                        client-secret: DmFrteIquh16FVqcoO4rLX81dTJIiQ69

                        client-authentication-method: client_secret_post
                        scope:
                            - profile_nickname
                            - profile_image


                    google:
                        client-id: 798155618029-5l08jbeia24v5k5jvq605sojv2uml6os.apps.googleusercontent.com
                        client-secret: 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
                        redirect-uri: http://ec2-43.200.184.246.ap-northeast-2.compute.amazonaws.com
                        scope:
                            - email
                            - profile
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
server:
    error:
        path: /error/500.html
    port: 8080
    servlet:
        context-path: /lotteshop

# 파일 업로드 설정
file:
 #   upload:
  #      path: /home/lotteshop/uploads/
    upload:
        path: uploads/

    # 개발용



mybatis:
    mapper-locations: classpath:mappers/**/*.xml